// taihu 远程访问层协议定义（设计文档_v3 §3）。
// Put client 流式上传（首帧带 key+size）；Get server 流式下发（支持 off/size 区间，size=-1 全量）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: rpc/storage.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObjectStore_Put_FullMethodName    = "/taihu.rpc.ObjectStore/Put"
	ObjectStore_Get_FullMethodName    = "/taihu.rpc.ObjectStore/Get"
	ObjectStore_Delete_FullMethodName = "/taihu.rpc.ObjectStore/Delete"
	ObjectStore_Stat_FullMethodName   = "/taihu.rpc.ObjectStore/Stat"
)

// ObjectStoreClient is the client API for ObjectStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ObjectStore 对象存储远程服务。
type ObjectStoreClient interface {
	// Put 上传对象：首帧携带 header{key,size}，其后为数据块；EOF 结束流。
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunk, PutResp], error)
	// Get 下载对象区间：off/size 相对对象起始，size=-1 表示读到对象结尾。
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunk], error)
	// Delete 删除对象映射。
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
	// Stat 返回对象逻辑大小。
	Stat(ctx context.Context, in *StatReq, opts ...grpc.CallOption) (*StatResp, error)
}

type objectStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectStoreClient(cc grpc.ClientConnInterface) ObjectStoreClient {
	return &objectStoreClient{cc}
}

func (c *objectStoreClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunk, PutResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObjectStore_ServiceDesc.Streams[0], ObjectStore_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutChunk, PutResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectStore_PutClient = grpc.ClientStreamingClient[PutChunk, PutResp]

func (c *objectStoreClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObjectStore_ServiceDesc.Streams[1], ObjectStore_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetReq, GetChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectStore_GetClient = grpc.ServerStreamingClient[GetChunk]

func (c *objectStoreClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, ObjectStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Stat(ctx context.Context, in *StatReq, opts ...grpc.CallOption) (*StatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResp)
	err := c.cc.Invoke(ctx, ObjectStore_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectStoreServer is the server API for ObjectStore service.
// All implementations must embed UnimplementedObjectStoreServer
// for forward compatibility.
//
// ObjectStore 对象存储远程服务。
type ObjectStoreServer interface {
	// Put 上传对象：首帧携带 header{key,size}，其后为数据块；EOF 结束流。
	Put(grpc.ClientStreamingServer[PutChunk, PutResp]) error
	// Get 下载对象区间：off/size 相对对象起始，size=-1 表示读到对象结尾。
	Get(*GetReq, grpc.ServerStreamingServer[GetChunk]) error
	// Delete 删除对象映射。
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
	// Stat 返回对象逻辑大小。
	Stat(context.Context, *StatReq) (*StatResp, error)
	mustEmbedUnimplementedObjectStoreServer()
}

// UnimplementedObjectStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectStoreServer struct{}

func (UnimplementedObjectStoreServer) Put(grpc.ClientStreamingServer[PutChunk, PutResp]) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedObjectStoreServer) Get(*GetReq, grpc.ServerStreamingServer[GetChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedObjectStoreServer) Delete(context.Context, *DeleteReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedObjectStoreServer) Stat(context.Context, *StatReq) (*StatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedObjectStoreServer) mustEmbedUnimplementedObjectStoreServer() {}
func (UnimplementedObjectStoreServer) testEmbeddedByValue()                     {}

// UnsafeObjectStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectStoreServer will
// result in compilation errors.
type UnsafeObjectStoreServer interface {
	mustEmbedUnimplementedObjectStoreServer()
}

func RegisterObjectStoreServer(s grpc.ServiceRegistrar, srv ObjectStoreServer) {
	// If the following call pancis, it indicates UnimplementedObjectStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectStore_ServiceDesc, srv)
}

func _ObjectStore_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObjectStoreServer).Put(&grpc.GenericServerStream[PutChunk, PutResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectStore_PutServer = grpc.ClientStreamingServer[PutChunk, PutResp]

func _ObjectStore_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObjectStoreServer).Get(m, &grpc.GenericServerStream[GetReq, GetChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObjectStore_GetServer = grpc.ServerStreamingServer[GetChunk]

func _ObjectStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStore_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Stat(ctx, req.(*StatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectStore_ServiceDesc is the grpc.ServiceDesc for ObjectStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taihu.rpc.ObjectStore",
	HandlerType: (*ObjectStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _ObjectStore_Delete_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _ObjectStore_Stat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _ObjectStore_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _ObjectStore_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/storage.proto",
}
