// taihu 远程访问层协议定义（设计文档_v3 §3）。
// Put client 流式上传（首帧带 key+size）；Get server 流式下发（支持 off/size 区间，size=-1 全量）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: rpc/storage.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *PutHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 仅首帧非空；其余帧 header 为空
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`     // 数据块（≤ 256KB）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunk) Reset() {
	*x = PutChunk{}
	mi := &file_rpc_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunk) ProtoMessage() {}

func (x *PutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunk.ProtoReflect.Descriptor instead.
func (*PutChunk) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{0}
}

func (x *PutChunk) GetHeader() *PutHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PutChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 对象逻辑大小（字节），0 <= size <= SegmentSizeBytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutHeader) Reset() {
	*x = PutHeader{}
	mi := &file_rpc_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutHeader) ProtoMessage() {}

func (x *PutHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutHeader.ProtoReflect.Descriptor instead.
func (*PutHeader) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{1}
}

func (x *PutHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResp) Reset() {
	*x = PutResp{}
	mi := &file_rpc_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResp) ProtoMessage() {}

func (x *PutResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResp.ProtoReflect.Descriptor instead.
func (*PutResp) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{2}
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Off           int64                  `protobuf:"varint,2,opt,name=off,proto3" json:"off,omitempty"`   // 相对对象起始偏移，>= 0
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // -1 = 读到结尾；否则 0 <= size 且 off+size <= 对象 Size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_rpc_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetReq) GetOff() int64 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *GetReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunk) Reset() {
	*x = GetChunk{}
	mi := &file_rpc_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunk) ProtoMessage() {}

func (x *GetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunk.ProtoReflect.Descriptor instead.
func (*GetChunk) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_rpc_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_rpc_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{6}
}

type StatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatReq) Reset() {
	*x = StatReq{}
	mi := &file_rpc_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReq) ProtoMessage() {}

func (x *StatReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReq.ProtoReflect.Descriptor instead.
func (*StatReq) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{7}
}

func (x *StatReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResp) Reset() {
	*x = StatResp{}
	mi := &file_rpc_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResp) ProtoMessage() {}

func (x *StatResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResp.ProtoReflect.Descriptor instead.
func (*StatResp) Descriptor() ([]byte, []int) {
	return file_rpc_storage_proto_rawDescGZIP(), []int{8}
}

func (x *StatResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_rpc_storage_proto protoreflect.FileDescriptor

const file_rpc_storage_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/storage.proto\x12\ttaihu.rpc\"L\n" +
	"\bPutChunk\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.taihu.rpc.PutHeaderR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"1\n" +
	"\tPutHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\t\n" +
	"\aPutResp\"@\n" +
	"\x06GetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03off\x18\x02 \x01(\x03R\x03off\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x1e\n" +
	"\bGetChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1d\n" +
	"\tDeleteReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\f\n" +
	"\n" +
	"DeleteResp\"\x1b\n" +
	"\aStatReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1e\n" +
	"\bStatResp\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size2\xd8\x01\n" +
	"\vObjectStore\x120\n" +
	"\x03Put\x12\x13.taihu.rpc.PutChunk\x1a\x12.taihu.rpc.PutResp(\x01\x12/\n" +
	"\x03Get\x12\x11.taihu.rpc.GetReq\x1a\x13.taihu.rpc.GetChunk0\x01\x125\n" +
	"\x06Delete\x12\x14.taihu.rpc.DeleteReq\x1a\x15.taihu.rpc.DeleteResp\x12/\n" +
	"\x04Stat\x12\x12.taihu.rpc.StatReq\x1a\x13.taihu.rpc.StatRespB\x1eZ\x1cgithub.com/liucxer/taihu/rpcb\x06proto3"

var (
	file_rpc_storage_proto_rawDescOnce sync.Once
	file_rpc_storage_proto_rawDescData []byte
)

func file_rpc_storage_proto_rawDescGZIP() []byte {
	file_rpc_storage_proto_rawDescOnce.Do(func() {
		file_rpc_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_storage_proto_rawDesc), len(file_rpc_storage_proto_rawDesc)))
	})
	return file_rpc_storage_proto_rawDescData
}

var file_rpc_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_storage_proto_goTypes = []any{
	(*PutChunk)(nil),   // 0: taihu.rpc.PutChunk
	(*PutHeader)(nil),  // 1: taihu.rpc.PutHeader
	(*PutResp)(nil),    // 2: taihu.rpc.PutResp
	(*GetReq)(nil),     // 3: taihu.rpc.GetReq
	(*GetChunk)(nil),   // 4: taihu.rpc.GetChunk
	(*DeleteReq)(nil),  // 5: taihu.rpc.DeleteReq
	(*DeleteResp)(nil), // 6: taihu.rpc.DeleteResp
	(*StatReq)(nil),    // 7: taihu.rpc.StatReq
	(*StatResp)(nil),   // 8: taihu.rpc.StatResp
}
var file_rpc_storage_proto_depIdxs = []int32{
	1, // 0: taihu.rpc.PutChunk.header:type_name -> taihu.rpc.PutHeader
	0, // 1: taihu.rpc.ObjectStore.Put:input_type -> taihu.rpc.PutChunk
	3, // 2: taihu.rpc.ObjectStore.Get:input_type -> taihu.rpc.GetReq
	5, // 3: taihu.rpc.ObjectStore.Delete:input_type -> taihu.rpc.DeleteReq
	7, // 4: taihu.rpc.ObjectStore.Stat:input_type -> taihu.rpc.StatReq
	2, // 5: taihu.rpc.ObjectStore.Put:output_type -> taihu.rpc.PutResp
	4, // 6: taihu.rpc.ObjectStore.Get:output_type -> taihu.rpc.GetChunk
	6, // 7: taihu.rpc.ObjectStore.Delete:output_type -> taihu.rpc.DeleteResp
	8, // 8: taihu.rpc.ObjectStore.Stat:output_type -> taihu.rpc.StatResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_storage_proto_init() }
func file_rpc_storage_proto_init() {
	if File_rpc_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_storage_proto_rawDesc), len(file_rpc_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_storage_proto_goTypes,
		DependencyIndexes: file_rpc_storage_proto_depIdxs,
		MessageInfos:      file_rpc_storage_proto_msgTypes,
	}.Build()
	File_rpc_storage_proto = out.File
	file_rpc_storage_proto_goTypes = nil
	file_rpc_storage_proto_depIdxs = nil
}
